/**
 *******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


 /****<MCAL ***********/
#include <stdint.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "NVIC_interface.h"

u8 pinValue;
int main(void)
{

/*******<< RCC **********/
 RCC_InitSysClock();

/********<< NVIC **********/

NVIC_EnableIRQ(35);
NVIC_SetPriority(35, 0, 15);

NVIC_DisableIRQ(35);

 /* Loop forever */

    while (1) 
    {


    }
}
