/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <BIT_MATH.h>
#include "STD_TYPES.h"

#include "TIM_interface.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
 #define REG(addr)   (*(volatile u32 *)(addr))
int main(void)
{

RCC_InitSysClock();
RCC_EnablePeripheralClock(RCC_APB1_BUS, RCC_APB1ENR_TIM2EN_BIT);
RCC_EnablePeripheralClock(RCC_AHB1_BUS, RCC_AHB1ENR_GPIOA_EN_BIT);

GPIO_SetPinMode(PORTA, GPIO_PIN_0, GPIO_MODE_AF);
GPIO_AF_Set(PORTA, GPIO_PIN_0, GPIO_AF_1);

TIM_voidInit(TIM_2);
TIM_voidSetCaptureCompareMode(TIM_2, CHANNEL_1, 0);
TIM_voidSetOutputCompareMode(TIM_2, CHANNEL_1, TIM_OC_PWM_MODE1);
TIM_voidSetPwmFrequency(TIM_2, 2000);      
TIM_voidSetDuty(TIM_2, CHANNEL_1, 10);
TIM_voidEnableChannel(TIM_2, CHANNEL_1);
TIM_voidStart(TIM_2);


    /* Loop forever */
	for(;;);
}
