/**
 *******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <BIT_MATH.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "STK_interface.h"

u8 g_u8ButtonState = 0;
void TogglePin(void)
{
    TOG_BIT(GPIOA_ODR, GPIO_PIN_7); 
}
int main(void)
{

 RCC_InitSysClock();

 RCC_EnablePeripheralClock(RCC_AHB1_BUS,RCC_AHB1ENR_GPIOB_EN_BIT);
 RCC_EnablePeripheralClock(RCC_AHB1_BUS,RCC_AHB1ENR_GPIOA_EN_BIT);

/******<< GPIOC 13 *****/

 GPIO_SetPinMode(PORTB, GPIO_PIN_0, GPIO_MODE_OUTPUT);
 GPIO_SetPinOutputType(PORTB, GPIO_PIN_0, GPIO_OUTPUT_TYPE_PUSH_PULL);
 GPIO_SetPinOutputSpeed(PORTB, GPIO_PIN_0, GPIO_OUTPUT_SPEED_LOW);
 GPIO_SetPinValue(PORTB, GPIO_PIN_0, GPIO_PIN_VALUE_HIGH);

/******<< GPIOA 7 *****/

 GPIO_SetPinMode(PORTA, GPIO_PIN_7, GPIO_MODE_OUTPUT);
 GPIO_SetPinOutputType(PORTA, GPIO_PIN_7, GPIO_OUTPUT_TYPE_PUSH_PULL);
 GPIO_SetPinOutputSpeed(PORTA, GPIO_PIN_7, GPIO_OUTPUT_SPEED_LOW);
 GPIO_SetPinValue(PORTA, GPIO_PIN_7, GPIO_PIN_VALUE_HIGH);

/******<< GPIOA 9 *****/

 GPIO_SetPinMode(PORTA, GPIO_PIN_9, GPIO_MODE_INPUT);
 GPIO_SetPinPullUpDown(PORTA, GPIO_PIN_9, GPIO_PULL_UP_DOWN_PULL_UP);

/************< STK >*************/
 STK_voidInit();

 /* Set the interval to 1000 ms */
 STK_SetIntervalPeriodic(TogglePin, 1000);
 /* Loop forever */

    while (1) 
    {
      

    }
}
