/**
 *******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"
int main(void)
{

 RCC_InitSysClock();
 RCC_EnablePeripheralClock(RCC_AHB1_BUS,RCC_AHB1ENR_GPIOC_EN_BIT);
   
 GPIO_SetPinMode(PORTC, GPIO_PIN_13, GPIO_MODE_OUTPUT);
 GPIO_SetPinOutputType(PORTC, GPIO_PIN_13, GPIO_OUTPUT_TYPE_PUSH_PULL);
 GPIO_SetPinOutputSpeed(PORTC, GPIO_PIN_13, GPIO_OUTPUT_SPEED_LOW);
 //GPIO_SetPinPullUpDown(PORTC, GPIO_PIN_13, GPIO_PULL_UP_DOWN_PULL_UP);
 GPIO_SetPinValue(PORTC, GPIO_PIN_13, GPIO_PIN_VALUE_LOW);
 /* Loop forever */

    while (1) 
    {
    }
}
