/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <BIT_MATH.h>
#include "STD_TYPES.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "STK_interface.h"
#include "NVIC_interface.h"
#include "EXTI_interface.h"
#include "EXTI_private.h"
/*************************< Global Variables *****************************/
volatile u32 PulseCounter = 0;
s64 PreviousTime = 0;
s64 CurrentTime = 0;
s64 INTERVAL = 1000;
f32 RPM = 0;
u8 Kp = 3;
f32 SetPoint = 50.0;
u8 PWM = 0;
f32 Error = 0;
u8 flag = 0;
/*************************<ControlDcMotor Function *****************************/
void ControlDcMotor(void)
{

  GPIO_GetPinValue(PORTA, GPIO_PIN_1,&flag)  ;
  if (flag == 1) PulseCounter++;
  else PulseCounter--;

}

int main(void)
{
    /* Initialize system clock */
      RCC_InitSysClock();
    /* Enable GPIO */
      RCC_EnablePeripheralClock(RCC_AHB1_BUS,RCC_AHB1ENR_GPIOC_EN_BIT);
      RCC_EnablePeripheralClock(RCC_AHB1_BUS,RCC_AHB1ENR_GPIOA_EN_BIT);
    /* configure GPIO pin as output */
    GPIO_SetPinMode(PORTC, GPIO_PIN_13, GPIO_MODE_OUTPUT); // Set PC13 as output
    GPIO_SetPinOutputType(PORTC, GPIO_PIN_13, GPIO_OUTPUT_TYPE_PUSH_PULL); // Set PC13 as push-pull
    GPIO_SetPinOutputSpeed(PORTC, GPIO_PIN_13, GPIO_OUTPUT_SPEED_LOW); //
    GPIO_SetPinValue(PORTC, GPIO_PIN_13, GPIO_PIN_VALUE_LOW); // Set PC13 high (LED off)
    /* Enable Alternate function clock */
     RCC_EnablePeripheralClock(RCC_APB2_BUS,RCC_APB2ENR_SYSCFGEN_BIT); // Enable clock


    /* Enable GPIOA PIN 0 and 1 as input*/
      GPIO_SetPinMode(PORTA, GPIO_PIN_0, GPIO_MODE_INPUT); // Set PA0 as input
      GPIO_SetPinPullUpDown(PORTA, GPIO_PIN_0, GPIO_PULL_UP_DOWN_PULL_DOWN); // Enable pull-up resistor for PA0
  
      GPIO_SetPinMode(PORTA, GPIO_PIN_1, GPIO_MODE_INPUT); // Set PA1- as input
      GPIO_SetPinPullUpDown(PORTA, GPIO_PIN_1, GPIO_PULL_UP_DOWN_PULL_DOWN); // Enable pull-up resistor for PA1

       
    /*Initialize GPIOA 7 */
      GPIO_SetPinMode(PORTA, GPIO_PIN_7, GPIO_MODE_OUTPUT);
      GPIO_SetPinOutputType(PORTA, GPIO_PIN_7, GPIO_OUTPUT_TYPE_PUSH_PULL);
      GPIO_SetPinOutputSpeed(PORTA, GPIO_PIN_7, GPIO_OUTPUT_SPEED_LOW);
      GPIO_SetPinValue(PORTA, GPIO_PIN_7, GPIO_PIN_VALUE_HIGH);
    
    
    /*Initialize GPIOA 6 */
      GPIO_SetPinMode(PORTA, GPIO_PIN_6, GPIO_MODE_OUTPUT);
      GPIO_SetPinOutputType(PORTA, GPIO_PIN_6, GPIO_OUTPUT_TYPE_PUSH_PULL);
      GPIO_SetPinOutputSpeed(PORTA, GPIO_PIN_6, GPIO_OUTPUT_SPEED_LOW);
      GPIO_SetPinValue(PORTA, GPIO_PIN_6, GPIO_PIN_VALUE_LOW);

    /*Enable EXTI1 from NVIC*/
      NVIC_EnableIRQ(6); 


    /* Configure EXTI1 line */
    EXTI_SelectPort(EXTI_LINE0, PORTA); // Select port A for EXTI line 7
    EXTI_SetTrigger(EXTI_LINE0, RISING_EDGE); // Set trigger to falling edge
    EXTI_EnableLine(EXTI_LINE0); // Enable EXTI line 7

    EXTI_SetCallBack(EXTI_LINE0, ControlDcMotor); // Set callback function for EXTI line 7
    /************< STK >*************/
     STK_voidInit();
      /* Loop forever */


	while(1)
    {
        /* Calculate RPM */
        CurrentTime = STK_Millis();
        if (CurrentTime - PreviousTime > INTERVAL)
        {
            RPM = ((PulseCounter /100.0) / 7.0)*60.0;
            PreviousTime = CurrentTime;
            PulseCounter = 0;
        }
}
}
